#!/usr/bin/env python3
"""profile_ref — an independent reference implementation of the normalized-hash profile.

Written from `docs/normalized-module-hash-profile.md` sections 3 and 4 ALONE, deliberately
without consulting `ffs.canon_unrebase`, and with NO third-party dependency (no pefile).

Why it exists
-------------
Conformance vectors generated by the implementation they are meant to test prove nothing --
they can only confirm that an implementation agrees with itself. This is the second
implementation the vectors are generated from and checked against, so a disagreement between
this and `canon_unrebase` is a real finding rather than a tautology.

It is also the honest test of whether the profile document is implementable by a stranger.
Every place the document did not say enough is recorded in GUESSES below, with the choice made.
Each entry is a defect in the document, not a note about this file.
"""
import hashlib
import struct

# ---------------------------------------------------------------------------
# GUESSES — where the profile text is silent and I had to decide. Each of these
# is a place two implementers could legitimately diverge. They are the edit list
# for the document.
# ---------------------------------------------------------------------------
GUESSES = [
    ("G1", "s4.1 said 'at the file offset corresponding to its RVA' but never defined the "
           "RVA->file-offset mapping. First chose max(VirtualSize,SizeOfRawData) as the span -- "
           "reverse-engineered from pefile rather than derived from the file -- and that guess was "
           "then written into the document as normative. CORRECTED: a section maps an rva only if "
           "it has raw bytes (PointerToRawData != 0, SizeOfRawData != 0) and "
           "VirtualAddress <= rva < VirtualAddress+SizeOfRawData; offset = "
           "PointerToRawData + (rva - VirtualAddress); overlaps: first match in table order. "
           "The widened span mapped an rva in a section's virtual-only tail onto the NEXT "
           "section's bytes and returned a confident wrong value. Verified byte-identical on all "
           "491 real modules before adopting, so no published value changed."),
    ("G2", "s4.1 never describes the relocation directory layout. Chose the PE/COFF standard: "
           "a sequence of blocks {PageRVA:u32, BlockSize:u32} followed by (BlockSize-8)/2 "
           "u16 entries, each type=entry>>12, offset=entry&0xFFF, target RVA=PageRVA+offset."),
    ("G3", "s4.1 never says where the base-relocation directory is found. Chose: DataDirectory "
           "index 5, at oh+96 (PE32) / oh+112 (PE32+), guarded by NumberOfRvaAndSizes at "
           "oh+92 / oh+108."),
    ("G4", "s4.1 does not say what 'no relocation directory' means concretely. Chose: "
           "NumberOfRvaAndSizes <= 5, OR directory RVA == 0, OR directory Size == 0."),
    ("G5", "s4.1 specifies failure only for unsupported relocation TYPES. It does not say what "
           "to do when a fixup target lies outside the image, when a block is malformed, or when "
           "the directory RVA maps to no section. Chose: fail, emit no value -- consistent with "
           "s2's 'MUST NOT emit a value it could not compute exactly'."),
    ("G6", "The section table location is never stated. Chose: sec = oh + SizeOfOptionalHeader "
           "(u16 at fh+16), NumberOfSections (u16 at fh+2), 40 bytes per entry."),
    ("G7", "s4.2 gives no bounds requirement. Chose: fail if the image is too short to hold the "
           "DOS header, the PE signature, the COFF header, or an optional header reaching oh+68."),
    ("G8", "The profile never says whether a relocation entry of type 0 (ABSOLUTE) with a "
           "non-zero offset should be skipped or treated as malformed. Chose: skip, per the "
           "table's 'padding, carries no fixup'."),
    ("G9", "FOUND BY REVIEW after the first cross-check. A data directory that cannot be READ "
           "(image ends before index 5) with B != 0 was treated as absent and emitted a "
           "header-only value -- the same fail-open canon_unrebase had. Two implementations "
           "agreeing on the reference did not catch it because both shared the blind spot. "
           "Now: fail. Also: an odd BlockSize was unspecified and emitted a value; now: fail."),
    ("G10", "FOUND BY REVIEW, second round. G4 treated every missing directory as an absence and "
            "emitted a header-only value. That is right for a module that genuinely has no "
            "relocations -- 1 of 491 real modules -- but wrong for one whose table was applied and "
            "then STRIPPED: its code still carries the load address, and the value would claim "
            "base 0. The two cases are distinguishable: IMAGE_FILE_RELOCS_STRIPPED (0x0001) in "
            "FileHeader.Characteristics at fh+18. Now: absent + flag clear -> value; absent + flag "
            "set with B != 0 -> fail. No real module sets the flag, so nothing observed changed."),
    ("G12", "FOUND BY REVIEW, third round. s4 said 'in order' but not WHAT each step reads. Two "
            "implementations that both apply fixups before zeroing still differed on crafted input: "
            "one read relocation entries from the untouched preimage, the other from the working copy. "
            "And s4.1 listed 'a section table past the end of the image' as a failure while this "
            "function only noticed it when it had a directory to walk. Now: the section table is "
            "located once, before s4.1, and must fit the image for any B; every other read in s4.1 is "
            "from the working copy. No real module is affected -- a real table always fits."),
]

ABSOLUTE, HIGHLOW, DIR64 = 0, 3, 10
RELOCS_STRIPPED = 0x0001          # IMAGE_FILE_RELOCS_STRIPPED, FileHeader.Characteristics
MAGIC_PE32, MAGIC_PE32PLUS = 0x10B, 0x20B
TE_SIGNATURE = b"VZ"               # EFI_TE_IMAGE_HEADER.Signature
TE_HEADER_SIZE = 40                # sizeof(EFI_TE_IMAGE_HEADER)


class NotNormalizable(Exception):
    """The profile says emit no value. Never a partially-normalized image."""


def _u16(b, o):
    return struct.unpack_from("<H", b, o)[0]


def _u32(b, o):
    return struct.unpack_from("<I", b, o)[0]


def _sections(buf, fh, oh):
    """(virtual_address, virtual_size, pointer_to_raw, size_of_raw) per section. [G6]"""
    n = _u16(buf, fh + 2)
    size_opt = _u16(buf, fh + 16)
    base = oh + size_opt
    out = []
    for i in range(n):
        s = base + i * 40
        if s + 40 > len(buf):
            raise NotNormalizable("section table past end of image")
        out.append((_u32(buf, s + 12), _u32(buf, s + 8), _u32(buf, s + 20), _u32(buf, s + 16)))
    return out


def _rva_to_offset(rva, sections):
    """[G1] s4.1: first section that has raw bytes in the file and contains rva.

    Bounded by SizeOfRawData, not by max(VirtualSize, SizeOfRawData): an rva in a
    section's virtual-only tail has no bytes on disk, and a widened span would map
    it onto whatever follows in the file -- normally the next section.
    """
    for va, _vsize, praw, rsize in sections:
        if praw == 0 or rsize == 0:
            continue
        if va <= rva < va + rsize:
            return praw + (rva - va)
    raise NotNormalizable("rva %#x maps to no section with raw data" % rva)


def normalize(preimage: bytes) -> bytes:
    """Profile s4 applied to a PE32/PE32+ preimage. Raises NotNormalizable where the
    profile says to emit no value."""
    buf = bytearray(preimage)

    # --- locate the headers (s4.2 layout, bounds per G7) ---
    if len(buf) < 0x40:
        raise NotNormalizable("shorter than a DOS header")
    e_lfanew = _u32(buf, 0x3C)
    if e_lfanew + 4 + 20 > len(buf):
        raise NotNormalizable("e_lfanew leaves no room for the COFF header")
    if bytes(buf[e_lfanew:e_lfanew + 4]) != b"PE\x00\x00":
        raise NotNormalizable("no PE signature at e_lfanew")
    fh = e_lfanew + 4
    oh = fh + 20
    if oh + 68 > len(buf):
        raise NotNormalizable("optional header truncated")

    magic = _u16(buf, oh)
    if magic == MAGIC_PE32:
        ib_off, ib_fmt, ib_w = oh + 28, "<I", 4
        numrva_off, dd_off = oh + 92, oh + 96
    elif magic == MAGIC_PE32PLUS:
        ib_off, ib_fmt, ib_w = oh + 24, "<Q", 8
        numrva_off, dd_off = oh + 108, oh + 112
    else:
        raise NotNormalizable("unsupported optional-header magic %#x" % magic)
    if ib_off + ib_w > len(buf):
        raise NotNormalizable("ImageBase field past end of image")
    B = struct.unpack_from(ib_fmt, buf, ib_off)[0]
    # [G12] The section table is located once, from the preimage, and that one table
    # serves both s4.1 and s4.2. It must lie inside the image whatever B is: s4.2
    # writes into every entry, and a table that runs off the end has no last entry.
    sec_tbl, nsec = oh + _u16(buf, fh + 16), _u16(buf, fh + 2)
    sections = _sections(buf, fh, oh)

    # --- s4.1 reverse the relocation fixups ---
    if B != 0:
        # An UNREADABLE directory is a failure, not an absence. The first version of this
        # function let a truncated data directory fall through to have_dir=False and
        # emitted a header-only value -- the identical fail-open class found in
        # canon_unrebase, reproduced independently here. Both implementations shared the
        # blind spot, so their agreement on the reference proved nothing about it.
        if numrva_off + 4 > len(buf):
            raise NotNormalizable("NumberOfRvaAndSizes unreadable with ImageBase != 0")
        have_dir = False
        if _u32(buf, numrva_off) > 5:                                      # [G3][G4]
            if dd_off + 6 * 8 > len(buf):
                raise NotNormalizable("data directory truncated before the base-relocation entry")
            reloc_rva = _u32(buf, dd_off + 5 * 8)
            reloc_size = _u32(buf, dd_off + 5 * 8 + 4)
            have_dir = reloc_rva != 0 and reloc_size != 0                 # [G4]
        # [G10] Absence and removal are different facts. With no directory and
        # IMAGE_FILE_RELOCS_STRIPPED set, the fixups were applied and the table then
        # discarded: nothing records which words were shifted, so the placement cannot
        # be reversed. Emitting a value here would return an image whose code still
        # carries its load address while its header claims base 0.
        if not have_dir and (_u16(buf, fh + 18) & RELOCS_STRIPPED):
            raise NotNormalizable("relocations stripped with ImageBase != 0; not reversible")
        if have_dir:
            start = _rva_to_offset(reloc_rva, sections)                   # [G1][G5]
            end = start + reloc_size
            if end > len(buf):
                raise NotNormalizable("relocation directory past end of image")  # [G5]
            p = start
            while p + 8 <= end:                                           # [G2]
                page_rva = _u32(buf, p)
                block_size = _u32(buf, p + 4)
                if block_size == 0:
                    break
                if block_size < 8 or p + block_size > end:
                    raise NotNormalizable("malformed relocation block")   # [G5]
                if (block_size - 8) % 2:
                    raise NotNormalizable("odd relocation BlockSize")      # entries are u16
                for q in range(p + 8, p + block_size, 2):
                    ent = _u16(buf, q)
                    rtype, roff = ent >> 12, ent & 0xFFF
                    if rtype == ABSOLUTE:                                 # [G8]
                        continue
                    if rtype not in (HIGHLOW, DIR64):
                        raise NotNormalizable("unsupported relocation type %d" % rtype)
                    target = _rva_to_offset(page_rva + roff, sections)
                    if rtype == HIGHLOW:
                        if target + 4 > len(buf):
                            raise NotNormalizable("HIGHLOW target past end")  # [G5]
                        v = _u32(buf, target)
                        struct.pack_into("<I", buf, target, (v - B) & 0xFFFFFFFF)
                    else:
                        if target + 8 > len(buf):
                            raise NotNormalizable("DIR64 target past end")    # [G5]
                        v = struct.unpack_from("<Q", buf, target)[0]
                        struct.pack_into("<Q", buf, target, (v - B) & ((1 << 64) - 1))
                p += block_size

    # --- s4.2 zero the placement-dependent header fields ---
    struct.pack_into("<I", buf, fh + 4, 0)          # TimeDateStamp
    struct.pack_into("<I", buf, oh + 64, 0)         # CheckSum
    struct.pack_into(ib_fmt, buf, ib_off, 0)        # ImageBase
    _zero_section_pointers(buf, sec_tbl, nsec)
    return bytes(buf)


def _zero_section_pointers(buf, sec_tbl, nsec):
    """[G11] PointerToRelocations and PointerToLinenumbers, every section header.

    These are COFF *object-file* fields and are zero in every linked image -- 993 of
    993 real modules measured. They are zeroed because GenFw's rebase stores the load
    address there: "Set base address into the first section header that doesn't point
    to code section" (BaseTools/Source/C/GenFw/GenFw.c:966-972), writing a UINT64 over
    the pair. That is placement-dependent data by definition, so it must not survive.
    """
    for i in range(nsec):
        struct.pack_into("<Q", buf, sec_tbl + i * 40 + 24, 0)   # table bounds checked by the caller


def _te_sections(buf, nsec):
    """Section table of a TE image: same 40-byte entries, at a fixed offset, holding
    ORIGINAL-PE coordinates (GenFw copies them verbatim and never rewrites them)."""
    out = []
    for i in range(nsec):
        h = TE_HEADER_SIZE + i * 40
        if h + 40 > len(buf):
            raise NotNormalizable("section table past end of image")
        out.append((_u32(buf, h + 12), _u32(buf, h + 8), _u32(buf, h + 20), _u32(buf, h + 16)))
    return out


def _te_rva_to_offset(rva, sections, tso):
    """The PE32 rule plus one constant: a TE file is the original PE with its first
    StrippedSize bytes replaced by a 40-byte header, so every original-PE offset moves
    down by (StrippedSize - 40). Cf. BasePeCoff.c:427-431."""
    for va, _vsize, praw, rsize in sections:
        if praw == 0 or rsize == 0:
            continue
        if va <= rva < va + rsize:
            return praw + (rva - va) - tso
    raise NotNormalizable("rva %#x maps to no section with raw data" % rva)


def normalize_te(preimage: bytes) -> bytes:
    """Profile `uefi-te-rebase0.v1` -- the TE sibling of `uefi-pe-rebase0.v1`.

    A TE header carries no TimeDateStamp and no CheckSum, so the PE32 profile's s4.2
    reduces to a single field here: ImageBase. Everything else is the same operation.
    """
    buf = bytearray(preimage)
    if len(buf) < TE_HEADER_SIZE or bytes(buf[:2]) != TE_SIGNATURE:
        raise NotNormalizable("not a TE image")
    nsec = buf[4]
    stripped = _u16(buf, 6)
    if stripped <= TE_HEADER_SIZE:
        raise NotNormalizable("StrippedSize %d does not exceed the TE header" % stripped)
    tso = stripped - TE_HEADER_SIZE
    B = struct.unpack_from("<Q", buf, 16)[0]
    reloc_rva, reloc_size = struct.unpack_from("<II", buf, 24)   # DataDirectory[0] = BASERELOC
    sections = _te_sections(buf, nsec)                           # [G12] bounds, whatever B is

    if B != 0:
        if reloc_size == 0:
            # A TE has no Characteristics, so it cannot carry IMAGE_FILE_RELOCS_STRIPPED.
            # GenFw encodes the same fact in the directory instead: it writes a bogus
            # NON-ZERO VirtualAddress with Size 0 to mean "relocatable, no fixups"
            # (GenFw.c:2700-2712), precisely because loaders read VA == 0 && Size == 0
            # as "relocations stripped" (MdePkg BasePeCoff.c:660-661). So VA is the
            # discriminator here, and it plays the role RELOCS_STRIPPED plays for PE32.
            if reloc_rva == 0:
                raise NotNormalizable("relocations stripped with ImageBase != 0; not reversible")
        else:
            start = _te_rva_to_offset(reloc_rva, sections, tso)
            end = start + reloc_size
            if start < 0 or end > len(buf):
                raise NotNormalizable("relocation directory past end of image")
            p = start
            while p + 8 <= end:
                page_rva = _u32(buf, p)
                block_size = _u32(buf, p + 4)
                if block_size == 0:
                    break
                if block_size < 8 or p + block_size > end:
                    raise NotNormalizable("malformed relocation block")
                if (block_size - 8) % 2:
                    raise NotNormalizable("odd relocation BlockSize")
                for q in range(p + 8, p + block_size, 2):
                    ent = _u16(buf, q)
                    rtype, roff = ent >> 12, ent & 0xFFF
                    if rtype == ABSOLUTE:
                        continue
                    if rtype not in (HIGHLOW, DIR64):
                        raise NotNormalizable("unsupported relocation type %d" % rtype)
                    target = _te_rva_to_offset(page_rva + roff, sections, tso)
                    if target < 0:
                        raise NotNormalizable("fixup target precedes the image")
                    if rtype == HIGHLOW:
                        if target + 4 > len(buf):
                            raise NotNormalizable("HIGHLOW target past end")
                        v = _u32(buf, target)
                        struct.pack_into("<I", buf, target, (v - B) & 0xFFFFFFFF)
                    else:
                        if target + 8 > len(buf):
                            raise NotNormalizable("DIR64 target past end")
                        v = struct.unpack_from("<Q", buf, target)[0]
                        struct.pack_into("<Q", buf, target, (v - B) & ((1 << 64) - 1))
                p += block_size

    _zero_section_pointers(buf, TE_HEADER_SIZE, nsec)
    struct.pack_into("<Q", buf, 16, 0)              # TE ImageBase
    return bytes(buf)


def digest(preimage: bytes) -> str:
    """s4.3 — SHA-256, lowercase hex. None-equivalent cases raise."""
    return hashlib.sha256(normalize(preimage)).hexdigest()


def digest_te(preimage: bytes) -> str:
    """`uefi-te-rebase0.v1` digest — SHA-256, lowercase hex."""
    return hashlib.sha256(normalize_te(preimage)).hexdigest()


if __name__ == "__main__":
    print("Reference implementation of the normalized-hash profile (no dependencies).")
    print(f"\n{len(GUESSES)} places the document did not say enough:\n")
    for tag, text in GUESSES:
        print(f"  [{tag}] {text}\n")
