#!/usr/bin/env python3
"""profile_ref — an independent reference implementation of the normalized-hash profile.

Written from `docs/normalized-module-hash-profile.md` sections 3 and 4 ALONE, deliberately
without consulting `ffs.canon_unrebase`, and with NO third-party dependency (no pefile).

Why it exists
-------------
Conformance vectors generated by the implementation they are meant to test prove nothing --
they can only confirm that an implementation agrees with itself. This is the second
implementation the vectors are generated from and checked against, so a disagreement between
this and `canon_unrebase` is a real finding rather than a tautology.

It is also the honest test of whether the profile document is implementable by a stranger.
Every place the document did not say enough is recorded in GUESSES below, with the choice made.
Each entry is a defect in the document, not a note about this file.
"""
import hashlib
import struct

# ---------------------------------------------------------------------------
# GUESSES — where the profile text is silent and I had to decide. Each of these
# is a place two implementers could legitimately diverge. They are the edit list
# for the document.
# ---------------------------------------------------------------------------
GUESSES = [
    ("G1", "s4.1 says 'at the file offset corresponding to its RVA' but never defines the "
           "RVA->file-offset mapping. Chose: find the section whose "
           "[VirtualAddress, VirtualAddress+max(VirtualSize,SizeOfRawData)) contains the RVA, "
           "then offset = PointerToRawData + (rva - VirtualAddress). Ties/overlaps: first match."),
    ("G2", "s4.1 never describes the relocation directory layout. Chose the PE/COFF standard: "
           "a sequence of blocks {PageRVA:u32, BlockSize:u32} followed by (BlockSize-8)/2 "
           "u16 entries, each type=entry>>12, offset=entry&0xFFF, target RVA=PageRVA+offset."),
    ("G3", "s4.1 never says where the base-relocation directory is found. Chose: DataDirectory "
           "index 5, at oh+96 (PE32) / oh+112 (PE32+), guarded by NumberOfRvaAndSizes at "
           "oh+92 / oh+108."),
    ("G4", "s4.1 does not say what 'no relocation directory' means concretely. Chose: "
           "NumberOfRvaAndSizes <= 5, OR directory RVA == 0, OR directory Size == 0."),
    ("G5", "s4.1 specifies failure only for unsupported relocation TYPES. It does not say what "
           "to do when a fixup target lies outside the image, when a block is malformed, or when "
           "the directory RVA maps to no section. Chose: fail, emit no value -- consistent with "
           "s2's 'MUST NOT emit a value it could not compute exactly'."),
    ("G6", "The section table location is never stated. Chose: sec = oh + SizeOfOptionalHeader "
           "(u16 at fh+16), NumberOfSections (u16 at fh+2), 40 bytes per entry."),
    ("G7", "s4.2 gives no bounds requirement. Chose: fail if the image is too short to hold the "
           "DOS header, the PE signature, the COFF header, or an optional header reaching oh+68."),
    ("G8", "The profile never says whether a relocation entry of type 0 (ABSOLUTE) with a "
           "non-zero offset should be skipped or treated as malformed. Chose: skip, per the "
           "table's 'padding, carries no fixup'."),
]

ABSOLUTE, HIGHLOW, DIR64 = 0, 3, 10
MAGIC_PE32, MAGIC_PE32PLUS = 0x10B, 0x20B


class NotNormalizable(Exception):
    """The profile says emit no value. Never a partially-normalized image."""


def _u16(b, o):
    return struct.unpack_from("<H", b, o)[0]


def _u32(b, o):
    return struct.unpack_from("<I", b, o)[0]


def _sections(buf, fh, oh):
    """(virtual_address, virtual_size, pointer_to_raw, size_of_raw) per section. [G6]"""
    n = _u16(buf, fh + 2)
    size_opt = _u16(buf, fh + 16)
    base = oh + size_opt
    out = []
    for i in range(n):
        s = base + i * 40
        if s + 40 > len(buf):
            raise NotNormalizable("section table past end of image")
        out.append((_u32(buf, s + 12), _u32(buf, s + 8), _u32(buf, s + 20), _u32(buf, s + 16)))
    return out


def _rva_to_offset(rva, sections):
    """[G1] first section whose virtual span contains rva."""
    for va, vsize, praw, rsize in sections:
        span = max(vsize, rsize)
        if va <= rva < va + span:
            return praw + (rva - va)
    raise NotNormalizable("rva %#x maps to no section" % rva)


def normalize(preimage: bytes) -> bytes:
    """Profile s4 applied to a PE32/PE32+ preimage. Raises NotNormalizable where the
    profile says to emit no value."""
    buf = bytearray(preimage)

    # --- locate the headers (s4.2 layout, bounds per G7) ---
    if len(buf) < 0x40:
        raise NotNormalizable("shorter than a DOS header")
    e_lfanew = _u32(buf, 0x3C)
    if e_lfanew + 4 + 20 > len(buf):
        raise NotNormalizable("e_lfanew leaves no room for the COFF header")
    if bytes(buf[e_lfanew:e_lfanew + 4]) != b"PE\x00\x00":
        raise NotNormalizable("no PE signature at e_lfanew")
    fh = e_lfanew + 4
    oh = fh + 20
    if oh + 68 > len(buf):
        raise NotNormalizable("optional header truncated")

    magic = _u16(buf, oh)
    if magic == MAGIC_PE32:
        ib_off, ib_fmt, ib_w = oh + 28, "<I", 4
        numrva_off, dd_off = oh + 92, oh + 96
    elif magic == MAGIC_PE32PLUS:
        ib_off, ib_fmt, ib_w = oh + 24, "<Q", 8
        numrva_off, dd_off = oh + 108, oh + 112
    else:
        raise NotNormalizable("unsupported optional-header magic %#x" % magic)
    if ib_off + ib_w > len(buf):
        raise NotNormalizable("ImageBase field past end of image")
    B = struct.unpack_from(ib_fmt, buf, ib_off)[0]

    # --- s4.1 reverse the relocation fixups ---
    if B != 0:
        have_dir = False
        if numrva_off + 4 <= len(buf) and _u32(buf, numrva_off) > 5:      # [G3][G4]
            if dd_off + 6 * 8 <= len(buf):
                reloc_rva = _u32(buf, dd_off + 5 * 8)
                reloc_size = _u32(buf, dd_off + 5 * 8 + 4)
                have_dir = reloc_rva != 0 and reloc_size != 0             # [G4]
        if have_dir:
            sections = _sections(buf, fh, oh)
            start = _rva_to_offset(reloc_rva, sections)                   # [G1][G5]
            end = start + reloc_size
            if end > len(buf):
                raise NotNormalizable("relocation directory past end of image")  # [G5]
            p = start
            while p + 8 <= end:                                           # [G2]
                page_rva = _u32(buf, p)
                block_size = _u32(buf, p + 4)
                if block_size == 0:
                    break
                if block_size < 8 or p + block_size > end:
                    raise NotNormalizable("malformed relocation block")   # [G5]
                for q in range(p + 8, p + block_size, 2):
                    ent = _u16(buf, q)
                    rtype, roff = ent >> 12, ent & 0xFFF
                    if rtype == ABSOLUTE:                                 # [G8]
                        continue
                    if rtype not in (HIGHLOW, DIR64):
                        raise NotNormalizable("unsupported relocation type %d" % rtype)
                    target = _rva_to_offset(page_rva + roff, sections)
                    if rtype == HIGHLOW:
                        if target + 4 > len(buf):
                            raise NotNormalizable("HIGHLOW target past end")  # [G5]
                        v = _u32(buf, target)
                        struct.pack_into("<I", buf, target, (v - B) & 0xFFFFFFFF)
                    else:
                        if target + 8 > len(buf):
                            raise NotNormalizable("DIR64 target past end")    # [G5]
                        v = struct.unpack_from("<Q", buf, target)[0]
                        struct.pack_into("<Q", buf, target, (v - B) & ((1 << 64) - 1))
                p += block_size

    # --- s4.2 zero the placement-dependent header fields ---
    struct.pack_into("<I", buf, fh + 4, 0)          # TimeDateStamp
    struct.pack_into("<I", buf, oh + 64, 0)         # CheckSum
    struct.pack_into(ib_fmt, buf, ib_off, 0)        # ImageBase
    return bytes(buf)


def digest(preimage: bytes) -> str:
    """s4.3 — SHA-256, lowercase hex. None-equivalent cases raise."""
    return hashlib.sha256(normalize(preimage)).hexdigest()


if __name__ == "__main__":
    print("Reference implementation of the normalized-hash profile (no dependencies).")
    print(f"\n{len(GUESSES)} places the document did not say enough:\n")
    for tag, text in GUESSES:
        print(f"  [{tag}] {text}\n")
