#!/usr/bin/env python3
"""Conformance tests for the normalized-module-hash profile.

Two independent implementations must agree: `ffs.canon_unrebase` (pefile) and
`profile_ref` (written from docs/normalized-module-hash-profile.md alone, no dependencies).
A conformance suite generated by the implementation it tests proves nothing, so the expected
values come from the reference and the pefile implementation is checked against them.

Hermetic: runs on the shipped synthetic vectors, no firmware image needed. The 122-module
reference cross-check needs pefile + a built OVMF and is a separate, loud SKIP.
"""
import base64
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "producers", "reconcile"))
import profile_ref  # noqa: E402

VECTORS = os.path.join(HERE, "..", "docs", "normalized-module-hash-vectors-synthetic.json")
fails = []


def check(cond, msg):
    print(("PASS  " if cond else "FAIL  ") + msg)
    if not cond:
        fails.append(msg)


def main():
    with open(VECTORS) as f:
        doc = json.load(f)
    vs = doc["vectors"]
    check(len(vs) >= 6, f"synthetic vectors present ({len(vs)})")

    # the reference reproduces its own vectors (guards accidental edits to profile_ref)
    for v in vs:
        raw = base64.b64decode(v["input_b64"])
        try:
            got = hashlib.sha256(profile_ref.normalize(raw)).hexdigest()
        except profile_ref.NotNormalizable:
            got = None
        check(got == v["sha256_norm"], f"reference reproduces vector: {v['id']}")

    # the pefile implementation agrees with the reference on every vector.
    try:
        from ffs import canon_unrebase, pefile
    except Exception:
        pefile = None
    if pefile is None:
        print("SKIP  canon_unrebase cross-check (pefile not installed — pip install -r requirements.txt)")
        print("⚠  the two-implementation agreement did NOT run here; CI installs pefile and runs it.")
    else:
        for v in vs:
            raw = base64.b64decode(v["input_b64"])
            try:
                got = hashlib.sha256(bytes(canon_unrebase(raw))).hexdigest()
            except Exception:
                got = None
            # Conformance model: an implementation MAY decline an input it cannot parse
            # (emitting no value is always safe). What is forbidden is emitting a value
            # that DIFFERS from the reference. So "no value" is acceptable everywhere;
            # a wrong value never is.
            if got is None:
                check(True, f"pefile declines (safe): {v['id']}")
            else:
                check(got == v["sha256_norm"],
                      f"pefile agrees with reference: {v['id']}")

    # the profile's own worked example, so the doc and the vectors cannot drift apart
    check(doc.get("expected_by", "").endswith("profile_ref.py"),
          "vectors declare they were produced by the reference, not by the tested implementation")

    print("\n" + ("ALL PASS" if not fails else f"{len(fails)} FAILED"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
